'use client';

import { useEffect, useRef, useState, useCallback, Suspense } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Zap, SkipForward, CheckCircle2, Clock, Cpu, Copy, Check, Link2, LogIn } from 'lucide-react';
import { getSocket } from '@/lib/socket';
import { useFaceMesh } from '@/hooks/useFaceMesh';
import { useWebRTC } from '@/hooks/useWebRTC';
import { FaceScore } from '@/lib/faceAnalysis';
import { Socket } from 'socket.io-client';
import ResultScreen from '@/components/ResultScreen';
import VideoPanel from '@/components/VideoPanel';
import QueueScreen from '@/components/QueueScreen';

function genUUID(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') return crypto.randomUUID();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = (Math.random() * 16) | 0;
    return (c === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}

type Phase = 'idle' | 'friend_lobby' | 'queuing' | 'connected' | 'analyzing' | 'waiting_opponent' | 'result';

interface MatchResult {
  scoreA: { score: FaceScore; traits: string[] };
  scoreB: { score: FaceScore; traits: string[] };
  winner: 'A' | 'B';
  winnerSocketId: string;
  eloResult?: { newRatingA: number; newRatingB: number; changeA: number; changeB: number };
}

function BattlePageInner() {
  const [phase, setPhase]             = useState<Phase>('idle');
  const [socket, setSocket]           = useState<Socket | null>(null);
  const [roomId, setRoomId]           = useState<string | null>(null);
  const [role, setRole]               = useState<'initiator' | 'receiver' | null>(null);
  const [queuePos, setQueuePos]       = useState(0);
  const [matchResult, setMatchResult] = useState<MatchResult | null>(null);
  const [mySocketId, setMySocketId]   = useState('');
  const [opponentLeft, setOpponentLeft] = useState(false);
  const [scoreSubmitted, setScoreSubmitted] = useState(false);

  // Friend battle state
  const [privateCode,  setPrivateCode]  = useState<string | null>(null);
  const [joinCode,     setJoinCode]     = useState('');
  const [copied,       setCopied]       = useState(false);
  const [privateError, setPrivateError] = useState<string | null>(null);

  // Auto-enter friend lobby if ?mode=friend in URL
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      if (params.get('mode') === 'friend') setPhase('friend_lobby');
    }
  }, []);

  // Auto-generate code when entering friend lobby
  const hasAutoGeneratedRef = useRef(false);
  useEffect(() => {
    if (phase === 'friend_lobby' && !privateCode) {
      const sid = localStorage.getItem('sessionId') || genUUID();
      localStorage.setItem('sessionId', sid);
      const s = getSocket();
      
      const requestRoom = () => {
        if (!hasAutoGeneratedRef.current) {
          hasAutoGeneratedRef.current = true;
          s.emit('create_private_room', { sessionId: sid });
          console.log('[Battle] Requested private room code...');
        }
      };

      if (s.connected) {
        requestRoom();
      } else {
        s.connect();
        s.once('connect', requestRoom);
      }
    }
    // Reset if we leave the lobby
    if (phase !== 'friend_lobby') {
      hasAutoGeneratedRef.current = false;
    }
  }, [phase, privateCode]);

  // SERVER-SYNCED countdown state
  const [countdown, setCountdown]     = useState<number | null>(null);
  const countdownIntervalRef          = useRef<NodeJS.Timeout | null>(null);
  const serverStartTimeRef            = useRef<number>(0);
  const countdownDurationRef          = useRef<number>(10000);

  // Track if we've sent peer_ready to server
  const peerReadySentRef = useRef(false);

  const localVideoRef  = useRef<HTMLVideoElement | null>(null);
  const remoteVideoRef = useRef<HTMLVideoElement | null>(null);

  const { localStream, remoteStream, connected: peerConnected } = useWebRTC({ socket, roomId, role });
  const {
    score: myScore, faceDetected, initState,
    startAnalysis, stopAnalysis, preInit, getFinalScore,
  } = useFaceMesh(localVideoRef);

  // Bind video streams to video elements
  useEffect(() => {
    if (localVideoRef.current  && localStream)  localVideoRef.current.srcObject  = localStream;
  }, [localStream]);
  useEffect(() => {
    if (remoteVideoRef.current && remoteStream) remoteVideoRef.current.srcObject = remoteStream;
  }, [remoteStream]);

  // Pre-load the AI model as soon as this page mounts — before any match
  useEffect(() => { preInit(); }, [preInit]);

  // ── When WebRTC peer stream arrives → tell server we're ready ──────────
  // Also: 20s timeout fallback so countdown isn't blocked if WebRTC is slow
  const peerReadyTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    if (peerConnected && remoteStream && socket && roomId && !peerReadySentRef.current) {
      peerReadySentRef.current = true;
      if (peerReadyTimeoutRef.current) clearTimeout(peerReadyTimeoutRef.current);
      socket.emit('peer_ready', { roomId });
      console.log('[Battle] peer_ready sent (stream connected)');
    }
  }, [peerConnected, remoteStream, socket, roomId]);

  // 10s timeout: send peer_ready even if WebRTC stream never arrives
  useEffect(() => {
    if (phase === 'connected' && socket && roomId && !peerReadySentRef.current) {
      peerReadyTimeoutRef.current = setTimeout(() => {
        if (!peerReadySentRef.current && socket && roomId) {
          peerReadySentRef.current = true;
          socket.emit('peer_ready', { roomId });
          console.log('[Battle] peer_ready sent (10s timeout fallback)');
        }
      }, 10000);
    }
    return () => {
      if (peerReadyTimeoutRef.current) clearTimeout(peerReadyTimeoutRef.current);
    };
  }, [phase, socket, roomId]);

  // ── Server-synced countdown helpers ────────────────────────────────────
  const startLocalCountdown = useCallback((serverTime: number, durationMs: number) => {
    serverStartTimeRef.current  = serverTime;
    countdownDurationRef.current = durationMs;

    if (countdownIntervalRef.current) clearInterval(countdownIntervalRef.current);

    const tick = () => {
      const elapsed = Date.now() - serverTime;
      const remaining = Math.max(0, Math.ceil((durationMs - elapsed) / 1000));
      setCountdown(remaining);
      if (remaining <= 0) {
        if (countdownIntervalRef.current) clearInterval(countdownIntervalRef.current);
      }
    };
    tick();
    countdownIntervalRef.current = setInterval(tick, 200); // 200ms for smooth display
  }, []);

  const submitScore = useCallback(() => {
    if (scoreSubmitted || !socket || !roomId) return;
    const final = getFinalScore();
    const score = final || { total: 5.0, symmetry: 0.5, jawScore: 0.5, eyeScore: 0.5, harmony: 0.5, traits: ['🤷 No Score'], verdict: 'N/A' };
    setScoreSubmitted(true);
    setPhase('waiting_opponent');
    socket.emit('submit_score', { roomId, score, traits: score.traits });
    stopAnalysis();
    if (countdownIntervalRef.current) clearInterval(countdownIntervalRef.current);
    console.log('[Battle] Score submitted:', score.total);
  }, [scoreSubmitted, getFinalScore, socket, roomId, stopAnalysis]);

  // ── Refs so socket handlers always call latest callbacks without re-init ──
  const submitScoreRef        = useRef(submitScore);
  const startAnalysisRef      = useRef(startAnalysis);
  const stopAnalysisRef       = useRef(stopAnalysis);
  const startLocalCountdownRef= useRef(startLocalCountdown);
  useEffect(() => { submitScoreRef.current         = submitScore;        }, [submitScore]);
  useEffect(() => { startAnalysisRef.current       = startAnalysis;      }, [startAnalysis]);
  useEffect(() => { stopAnalysisRef.current        = stopAnalysis;       }, [stopAnalysis]);
  useEffect(() => { startLocalCountdownRef.current = startLocalCountdown;}, [startLocalCountdown]);

  // ── Socket setup (runs ONCE on mount — no dependency churn) ─────────────
  useEffect(() => {
    const s = getSocket();
    s.connect();
    setSocket(s);

    s.on('connect', () => setMySocketId(s.id || ''));
    s.on('queue_position', ({ position }: { position: number }) => setQueuePos(position));

    s.on('matched', ({ roomId: rid, role: r }: { roomId: string; role: 'initiator' | 'receiver' }) => {
      setRoomId(rid); setRole(r); setPhase('connected');
      setOpponentLeft(false); peerReadySentRef.current = false; setPrivateCode(null);
    });

    s.on('private_room_created', ({ code }: { code: string }) => setPrivateCode(code));
    s.on('private_room_error',   ({ message }: { message: string }) => setPrivateError(message));

    s.on('countdown_start', ({ serverTime, durationMs }: { serverTime: number; durationMs: number }) => {
      setPhase('analyzing');
      startLocalCountdownRef.current(serverTime, durationMs);
      startAnalysisRef.current();
    });

    s.on('submit_now', () => submitScoreRef.current());

    s.on('opponent_left', () => {
      setOpponentLeft(true);
      stopAnalysisRef.current();
      if (countdownIntervalRef.current) clearInterval(countdownIntervalRef.current);
      setCountdown(null);
      setTimeout(() => setOpponentLeft(false), 3500);
    });

    s.on('match_result', (r: MatchResult) => {
      setMatchResult(r); setPhase('result');
      stopAnalysisRef.current();
      if (countdownIntervalRef.current) clearInterval(countdownIntervalRef.current);
    });

    return () => {
      s.off('connect'); s.off('queue_position'); s.off('matched');
      s.off('private_room_created'); s.off('private_room_error');
      s.off('countdown_start'); s.off('submit_now');
      s.off('opponent_left'); s.off('match_result');
      s.disconnect();
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Auto-submit when local countdown hits 0 ─────────────────────────────
  useEffect(() => {
    if (countdown === 0 && phase === 'analyzing' && !scoreSubmitted) {
      submitScore();
    }
  }, [countdown, phase, scoreSubmitted, submitScore]);

  // ── Queue helpers ────────────────────────────────────────────────────────
  const joinQueue = useCallback(() => {
    if (!socket) return;
    setPhase('queuing');
    setMatchResult(null);
    setScoreSubmitted(false);
    setCountdown(null);
    peerReadySentRef.current = false;
    const sid = localStorage.getItem('sessionId') || genUUID();
    localStorage.setItem('sessionId', sid);
    socket.emit('join_queue', { sessionId: sid });
  }, [socket]);

  const nextMatch = useCallback(() => {
    if (!socket) return;
    setPhase('queuing');
    setMatchResult(null);
    setScoreSubmitted(false);
    setCountdown(null);
    setOpponentLeft(false);
    peerReadySentRef.current = false;
    if (countdownIntervalRef.current) clearInterval(countdownIntervalRef.current);
    socket.emit('next_match');
  }, [socket]);

  const isWinner = matchResult?.winnerSocketId === mySocketId;
  const isUrgent = countdown !== null && countdown <= 3;

  return (
    <div className="page">
      {/* ── NAV ── */}
      <nav className="nav">
        <a href="/" className="nav-logo" style={{ display: 'flex', alignItems: 'center' }}>
          <img src="/logo.png" alt="Ommogale" style={{ height: 56, objectFit: 'contain' }} />
        </a>
        <div className="nav-actions">
          {initState === 'loading' && (
            <div className="flex items-center gap-2" style={{ fontSize: 12, color: '#fbbf24' }}>
              <Cpu size={12} color="#fbbf24" />
              <span>Loading AI<span className="loading-dots"><span>.</span><span>.</span><span>.</span></span></span>
            </div>
          )}
          {myScore && phase === 'analyzing' && (
            <motion.div className="card flex items-center gap-2"
              style={{ padding: '6px 12px', borderRadius: 99 }}
              initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }}>
              <div className="dot dot-green" style={{ animation: 'pulse-glow 1.5s ease-in-out infinite' }} />
              <span className="text-green font-semibold" style={{ fontSize: 13 }}>
                {myScore.total.toFixed(1)}
              </span>
            </motion.div>
          )}
          {phase !== 'idle' && phase !== 'queuing' && (
            <button id="skip-btn" className="btn btn-ghost btn-sm" onClick={nextMatch}>
              <SkipForward size={14} /> Skip
            </button>
          )}
        </div>
      </nav>

      {/* ── MAIN ── */}
      <main className="page-content">
        <AnimatePresence mode="wait">

          {/* FRIEND LOBBY */}
          {phase === 'friend_lobby' && (
            <motion.div key="friend" className="container-md text-center"
              initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>

              <h2 style={{ fontSize: 28, fontWeight: 600, marginBottom: 8, color: '#f8fafc' }}>Friend Battle</h2>
              <p style={{ color: '#94a3b8', fontSize: 15, marginBottom: 32 }}>Challenge a specific friend — share a code or enter theirs</p>

              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 20, marginBottom: 24, textAlign: 'left' }}>

                {/* CREATE ROOM */}
                <div style={{ flex: '1 1 240px', padding: 24, borderRadius: 12, background: '#0f1115', border: '1px solid #1e222a' }}>
                  <h3 style={{ fontSize: 14, fontWeight: 600, color: '#f8fafc', marginBottom: 6 }}>Your Code</h3>
                  <p style={{ fontSize: 13, color: '#64748b', marginBottom: 16 }}>Share this code with your friend</p>
                  {privateCode ? (
                    <>
                      <div style={{ fontSize: 28, letterSpacing: '0.1em', fontWeight: 600, color: '#f8fafc', textAlign: 'center', background: '#181b21', padding: '16px 0', borderRadius: 8, marginBottom: 16 }}>
                        {privateCode}
                      </div>
                      <button style={{ width: '100%', padding: '10px 0', background: '#f8fafc', color: '#050508', border: 'none', borderRadius: 8, fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, cursor: 'pointer' }}
                        onClick={() => { navigator.clipboard.writeText(privateCode); setCopied(true); setTimeout(() => setCopied(false), 2000); }}>
                        {copied ? <><Check size={16} /> Copied</> : <><Copy size={16} /> Copy Code</>}
                      </button>
                      <p style={{ textAlign: 'center', fontSize: 13, color: '#64748b', marginTop: 16 }}>Waiting for friend...</p>
                    </>
                  ) : (
                    <div style={{ textAlign: 'center', padding: '24px 0' }}>
                      <p style={{ fontSize: 13, color: '#64748b' }}>Generating...</p>
                    </div>
                  )}
                </div>

                {/* JOIN ROOM */}
                <div style={{ flex: '1 1 240px', padding: 24, borderRadius: 12, background: '#0f1115', border: '1px solid #1e222a' }}>
                  <h3 style={{ fontSize: 14, fontWeight: 600, color: '#f8fafc', marginBottom: 6 }}>Join Room</h3>
                  <p style={{ fontSize: 13, color: '#64748b', marginBottom: 16 }}>Enter the code your friend shared</p>
                  <input
                    type="text" maxLength={6} placeholder="CODE"
                    value={joinCode}
                    onChange={e => { setJoinCode(e.target.value.toUpperCase()); setPrivateError(null); }}
                    style={{
                      width: '100%', background: '#181b21', border: '1px solid #2a2f3a', borderRadius: 8,
                      padding: '16px 12px', color: '#f8fafc', fontSize: 20, letterSpacing: '0.1em',
                      textAlign: 'center', marginBottom: 16, outline: 'none',
                    }}
                  />
                  <button style={{ width: '100%', padding: '10px 0', background: joinCode.length < 4 ? '#2a2f3a' : '#f8fafc', color: joinCode.length < 4 ? '#64748b' : '#050508', border: 'none', borderRadius: 8, fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, cursor: joinCode.length < 4 ? 'not-allowed' : 'pointer', transition: 'all 0.2s' }}
                    disabled={joinCode.length < 4}
                    onClick={() => {
                      const sid = localStorage.getItem('sessionId') || genUUID();
                      localStorage.setItem('sessionId', sid);
                      const s = getSocket();
                      if (!s.connected) s.connect();
                      s.emit('join_private_room', { code: joinCode, sessionId: sid });
                      setPrivateError(null);
                    }}>
                    <LogIn size={16} /> Join Battle
                  </button>
                </div>
              </div>

              {privateError && (
                <div style={{ background: '#1f1315', border: '1px solid #4a1c22', color: '#f87171', padding: '12px', borderRadius: 8, marginBottom: 16, fontSize: 14 }}>
                  {privateError}
                </div>
              )}

              <button style={{ background: 'none', border: 'none', color: '#94a3b8', fontSize: 14, cursor: 'pointer', padding: '8px 16px' }} onClick={() => { setPhase('idle'); setPrivateCode(null); setJoinCode(''); }}>
                ← Back
              </button>
            </motion.div>
          )}

          {/* IDLE */}
          {phase === 'idle' && (
            <motion.div key="idle" className="text-center container-sm"
              initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -30 }}>
              <h2 style={{ fontSize: 48, fontWeight: 700, color: '#f8fafc', marginBottom: 16, letterSpacing: '0.05em' }}>
                READY?
              </h2>
              <p style={{ color: '#94a3b8', fontSize: 16, maxWidth: 420, margin: '0 auto 32px', lineHeight: 1.6 }}>
                You&apos;ll be matched with a random stranger. Both cameras go live, a 10-second AI analysis runs, and the server decides who mogged who.
              </p>
              <motion.button id="start-battle-btn" 
                style={{ background: '#f8fafc', color: '#050508', border: 'none', borderRadius: 8, padding: '16px 32px', fontSize: 16, fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}
                whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} onClick={joinQueue}>
                <Zap size={18} strokeWidth={2.5} /> Start Battle
              </motion.button>
            </motion.div>
          )}

          {/* QUEUING */}
          {phase === 'queuing' && (
            <motion.div key="queuing" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              <QueueScreen position={queuePos} onCancel={() => { socket?.emit('leave_queue'); setPhase('idle'); }} />
            </motion.div>
          )}

          {/* BATTLE / ANALYZING / WAITING */}
          {(phase === 'connected' || phase === 'analyzing' || phase === 'waiting_opponent') && (
            <motion.div key="battle" className="w-full container-lg"
              initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }}>

              {/* Opponent left banner */}
              <AnimatePresence>
                {opponentLeft && (
                  <motion.div className="card card-pink text-center"
                    style={{ padding: '12px 20px', marginBottom: 16, borderRadius: 14 }}
                    initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}>
                    <span className="neon-pink font-semibold">Opponent disconnected.</span>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* ── WAITING FOR OPPONENT ── */}
              {phase === 'connected' && (
                <motion.div
                  className="text-center"
                  style={{ padding: '20px 0 12px' }}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                >
                  {/* Big waiting text */}
                  <motion.div
                    className="font-display"
                    style={{
                      fontSize: 'clamp(28px, 6vw, 48px)',
                      letterSpacing: '0.08em',
                      background: 'linear-gradient(135deg, #a855f7, #00f5d4)',
                      WebkitBackgroundClip: 'text',
                      WebkitTextFillColor: 'transparent',
                      marginBottom: 8,
                    }}
                    animate={{ opacity: [1, 0.6, 1] }}
                    transition={{ duration: 1.8, repeat: Infinity, ease: 'easeInOut' }}
                  >
                    WAITING FOR OPPONENT
                  </motion.div>

                  {/* Animated dots */}
                  <div className="flex items-center justify-center gap-3" style={{ marginBottom: 8 }}>
                    {[0, 1, 2].map(i => (
                      <motion.div key={i}
                        style={{ width: 10, height: 10, borderRadius: '50%', background: '#a855f7' }}
                        animate={{ scale: [1, 1.6, 1], opacity: [0.4, 1, 0.4] }}
                        transition={{ duration: 1.2, repeat: Infinity, delay: i * 0.3 }}
                      />
                    ))}
                  </div>

                  <p className="text-muted" style={{ fontSize: 13 }}>
                    {peerConnected
                      ? 'Connected — waiting for both cameras to sync…'
                      : 'Connecting video streams…'
                    }
                  </p>
                </motion.div>
              )}

              {/* ── SERVER-SYNCED COUNTDOWN ── */}
              {phase === 'analyzing' && countdown !== null && (
                <motion.div className="text-center mb-4"
                  initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }}>
                  <motion.div
                    className="font-display"
                    style={{
                      fontSize: 'clamp(36px, 8vw, 64px)',
                      color: isUrgent ? '#ff2d78' : '#00f5d4',
                      textShadow: isUrgent
                        ? '0 0 40px rgba(255,45,120,0.9)'
                        : '0 0 30px rgba(0,245,212,0.8)',
                    }}
                    animate={isUrgent ? { scale: [1, 1.12, 1] } : {}}
                    transition={{ duration: 0.5, repeat: isUrgent ? Infinity : 0 }}
                  >
                    {initState !== 'ready' ? '⏳ AI Loading…' : `Analyzing… ${countdown}s`}
                  </motion.div>
                  {/* Progress bar synced to server time */}
                  <div className="score-bar mx-auto mt-3" style={{ height: 6, maxWidth: 320 }}>
                    <motion.div className="score-bar-fill"
                      style={{
                        background: isUrgent
                          ? 'linear-gradient(90deg, #ff2d78, #ff6b6b)'
                          : 'linear-gradient(90deg, #a855f7, #00f5d4)',
                        width: countdown !== null
                          ? `${((countdownDurationRef.current / 1000 - countdown) / (countdownDurationRef.current / 1000)) * 100}%`
                          : '0%',
                      }}
                      transition={{ duration: 0.2 }}
                    />
                  </div>
                </motion.div>
              )}

              {/* Video panels */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
                <VideoPanel videoRef={localVideoRef}  label="YOU"      score={phase === 'analyzing' ? myScore : null} isLocal={true}  faceDetected={faceDetected} color="cyan" />
                <VideoPanel videoRef={remoteVideoRef} label="OPPONENT" score={null}                                    isLocal={false} faceDetected={null}         color="pink" />
              </div>

              {/* Analyzing: AI model loading warning + lock-in button */}
              {phase === 'analyzing' && (
                <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
                  {initState !== 'ready' && (
                    <div className="card text-center mb-3" style={{
                      padding: '10px 20px', borderRadius: 14,
                      borderColor: 'rgba(251,191,36,0.4)',
                    }}>
                      <p style={{ color: '#fbbf24', fontSize: 13, fontWeight: 600 }}>
                        🤖 AI model loading (first-time ~15s) — score will auto-submit when ready
                      </p>
                    </div>
                  )}
                  <button id="lock-score-btn" className="btn btn-primary w-full"
                    style={{ width: '100%', fontFamily: 'var(--font-display)', fontSize: 20, letterSpacing: '0.12em', padding: '14px', borderRadius: 14 }}
                    onClick={submitScore}>
                    🔒 LOCK IN SCORE NOW
                  </button>
                </motion.div>
              )}

              {/* Waiting for opponent */}
              {phase === 'waiting_opponent' && (
                <motion.div className="card card-purple text-center"
                  style={{ padding: 28, borderRadius: 20 }}
                  initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
                  <div className="flex items-center justify-center gap-2 mb-2">
                    <CheckCircle2 size={22} color="#00f5d4" />
                    <span className="font-display neon-cyan" style={{ fontSize: 26 }}>Score Submitted</span>
                  </div>
                  <p className="text-secondary loading-dots">
                    Waiting for opponent <span>.</span><span>.</span><span>.</span>
                  </p>
                </motion.div>
              )}
            </motion.div>
          )}

          {/* RESULT — full screen takeover */}
          {phase === 'result' && matchResult && (
            <ResultScreen
              result={matchResult}
              isWinner={isWinner}
              mySocketId={mySocketId}
              onNext={nextMatch}
              onHome={() => { window.location.href = '/'; }}
            />
          )}

        </AnimatePresence>
      </main>
    </div>
  );
}

export default function BattlePageClient() {
  return (
    <Suspense fallback={null}>
      <BattlePageInner />
    </Suspense>
  );
}
